In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [10]:
dataset = pd.read_csv("latest.csv")

In [11]:
dataset

,_id,Pathogen,ID,Case_status,Pathogen_status,Location_information,Age,Sex_at_birth,Sex_at_birth_other,Gender,...,Travel_history_start,Travel_history_location,Genomics_Metadata,Accession_Number,Source,Source_II,Source_III,Source_IV,Date_entry,Date_last_modified
0,63339f546231dbc49320096e,NaN,NaN,confirmed,NaN,"Non-US Resident, United States",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63339f546231dbc49320096f,NaN,NaN,confirmed,NaN,"Non-US Resident, United States",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,63339f546231dbc493200970,NaN,NaN,confirmed,NaN,"Non-US Resident, United States",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,63339f546231dbc493200972,NaN,NaN,confirmed,NaN,"Alabama, United States",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63339f546231dbc493200973,NaN,NaN,confirmed,NaN,"Alabama, United States",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81761,63e2e899deaa06b86747d1b5,NaN,NaN,confirmed,NaN,Spain,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81762,63e2e899deaa06b86747d1b6,NaN,NaN,confirmed,NaN,Spain,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81763,63e2e899deaa06b86747d1b7,NaN,NaN,confirmed,NaN,Spain,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81764,63e2e899deaa06b86747d1b8,NaN,NaN,confirmed,NaN,Spain,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81765,63e2e899deaa06b86747d1b9,NaN,NaN,confirmed,NaN,Spain,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN